const {chromium}=require(process.env.PLAYWRIGHT_MODULE_PATH || 'playwright');
const fs=require('fs');
const assert=require('node:assert/strict');
(async()=>{
const dir=process.env.QR_TEST_EVIDENCE_DIR;
assert.ok(dir,'Set QR_TEST_EVIDENCE_DIR to the authorized evidence directory');fs.mkdirSync(dir,{recursive:true});
const browser=await chromium.launch({executablePath:process.env.QR_TEST_CHROME_PATH,headless:true});
try{
const page=await browser.newPage({viewport:{width:390,height:844}});page.setDefaultTimeout(10000);page.on('pageerror',e=>console.error('PAGE',e.message));
await page.goto('file://'+process.cwd()+'/.browser-qr-test/index.html');
await page.getByRole('button',{name:'Start camera'}).waitFor();
const events=()=>page.evaluate(()=>window.events);
assert.deepEqual(await events(),[]);
await page.screenshot({path:dir+'/01-camera-off.png'});
await page.getByRole('button',{name:'Start camera'}).click();
await page.getByRole('alert').waitFor();
assert.deepEqual(await events(),[['cameraRequested']]);
await page.screenshot({path:dir+'/02-camera-denied.png'});
await page.getByRole('textbox').fill('https://evil.example/c/AbCdEfGhIjKlMnOpQrStUvWx');
await page.getByRole('button',{name:'Open card',exact:true}).click();
await page.getByText('Enter an OpenChat card link',{exact:false}).waitFor();
assert.deepEqual(await events(),[['cameraRequested']]);
await page.screenshot({path:dir+'/03-rejected-link.png'});
await page.getByRole('textbox').fill('https://chat.globalbr.ai/c/AbCdEfGhIjKlMnOpQrStUvWx');
await page.getByRole('button',{name:'Open card',exact:true}).click();
await page.getByRole('button',{name:'Add Alex Rivera as a friend'}).waitFor();
assert.deepEqual((await events()).map(e=>e[0]),['cameraRequested','navigate','getCard']);
await page.screenshot({path:dir+'/04-paste-opens-card.png'});
await page.getByRole('button',{name:'Save contact'}).click();
assert.deepEqual((await events()).at(-1),['saveContact','https://chat.globalbr.ai/api/card/AbCdEfGhIjKlMnOpQrStUvWx/contact.vcf']);
await page.getByRole('button',{name:'Add Alex Rivera as a friend'}).click();
await page.getByRole('button',{name:'Cancel friend request'}).waitFor();
assert.equal((await events()).at(-1)[0],'friendRequest');
assert.ok(!(await events()).some(e=>e[0]==='conversationCreated'));
await page.screenshot({path:dir+'/05-approval-pending.png'});
const pasteEvents=await events();
await page.evaluate(()=>{Object.defineProperty(navigator,'mediaDevices',{configurable:true,value:undefined});window.reset()});
await page.getByRole('button',{name:'Start camera'}).click();
await page.getByRole('alert').waitFor();
assert.deepEqual(await events(),[]);
await page.screenshot({path:dir+'/08-camera-unavailable.png'});
await page.getByRole('textbox').fill('openchat://card/AbCdEfGhIjKlMnOpQrStUvWx');
await page.getByRole('button',{name:'Open card',exact:true}).click();
await page.getByRole('button',{name:'Add Alex Rivera as a friend'}).waitFor();
assert.deepEqual((await events()).map(e=>e[0]),['navigate','getCard']);
// Reload restores the camera fixture before the frame-decoding checks.
await page.reload();
await page.getByRole('button',{name:'Start camera'}).waitFor();
await page.evaluate(()=>{window.cameraMode='success';window.cameraValue='https://evil.example/unsafe';window.reset()});
await page.getByRole('button',{name:'Start camera'}).click();
await page.getByText('This code is not an OpenChat card.',{exact:false}).waitFor();
assert.deepEqual(await events(),[['cameraRequested']]);
await page.screenshot({path:dir+'/06-unsupported-qr.png'});
await page.evaluate(()=>window.leave());
await page.getByText('Scanner closed').waitFor();
assert.deepEqual(await events(),[['cameraRequested'],['trackStopped']]);
assert.equal(await page.evaluate(()=>window.stream.getTracks()[0].readyState),'ended');
await page.evaluate(()=>{window.cameraValue='https://chat.globalbr.ai/c/'+window.token;window.reset()});
await page.getByRole('button',{name:'Start camera'}).click();
await page.getByRole('button',{name:'Add Alex Rivera as a friend'}).waitFor();
await page.waitForTimeout(1000);
assert.deepEqual((await events()).map(e=>e[0]),['cameraRequested','trackStopped','navigate','getCard']);
assert.equal(await page.evaluate(()=>window.stream.getTracks()[0].readyState),'ended');
await page.screenshot({path:dir+'/07-decoded-card.png'});
fs.writeFileSync(dir+'/browser-flow.json',JSON.stringify({fixture:'Actual ScanQrScreen.web and CardEntryScreen rendered with React Native Web; fixture navigation, API, and generated QR canvas MediaStream. Real jsQR decoder.',pasteAndRequest:pasteEvents,qrScan:await events(),unsupportedQr:'Rejected in real camera frame; no navigation; track ended on leaving',cameraConsent:'No getUserMedia call before Start camera',duplicates:'One navigation after continued frame wait'},null,2));
console.log('Browser flow verified: camera off until gesture; denial and unsafe-link rejection; paste opens review card; Save contact distinct; request remains pending without conversation; real QR rejects foreign code, stops on exit, and opens card once.');
}finally{await browser.close()}
})().catch(e=>{console.error(e);process.exitCode=1});
